// Generated by Wrangler on Mon Aug 19 2024 15:17:56 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
	AI: Ai;
}
