import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button, DarkThemeToggle, Navbar, NavbarBrand, NavbarCollapse, NavbarLink, NavbarToggle, ThemeModeScript } from "flowbite-react";
import { auth, signIn, signOut } from "@/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className + " bg-white dark:bg-slate-800 bg-opacity-0 h-max"}>
        <Navbar fluid>
          <NavbarBrand href={process.env.CF_PAGES_URL}>
            <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">Lära Svenska</span>
          </NavbarBrand>
          <div className="flex flex-row justify-between items-center gap-2 md:order-2">
            {
              session?.user ?
                <>
                  <img className="w-9 h-9" src={session.user.image}></img>
                  <form><Button type="submit" formAction={(async () => {
                    "use server";
                    await signOut()
                  }) as any}>Sign Out</Button>
                  </form>
                </>
                : <form>
                  <Button type="submit" formAction={(async () => {
                    "use server";
                    await signIn()
                  }) as any}>Signin</Button>
                </form>
            }
            <DarkThemeToggle />
            <NavbarToggle />
          </div>
          <NavbarCollapse>
            <NavbarLink href={process.env.CF_PAGES_URL + "/articles"}>Articles</NavbarLink>
          </NavbarCollapse>
        </Navbar>
        <main className="mx-auto w-full max-w-8xl lg:flex lg:px-4 text-slate-500 dark:text-slate-400">{children}</main>
      </body>
    </html>
  );
}
